<?php
/**
 * AgeVerifyFailureCode
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Avalara\ASV
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta.
 *
 * The version of the OpenAPI document: 2.1.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Avalara\ASV\Model;
use \Avalara\ASV\ObjectSerializer;

/**
 * AgeVerifyFailureCode Class Doc Comment
 *
 * @category Class
 * @package  Avalara\ASV
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AgeVerifyFailureCode
{
    /**
     * Possible values of this enum
     */
    const NOT_FOUND = 'not_found';

    const DOB_UNVERIFIABLE = 'dob_unverifiable';

    const UNDER_AGE = 'under_age';

    const SUSPECTED_FRAUD = 'suspected_fraud';

    const DECEASED = 'deceased';

    const UNKNOWN_ERROR = 'unknown_error';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_FOUND,
            self::DOB_UNVERIFIABLE,
            self::UNDER_AGE,
            self::SUSPECTED_FRAUD,
            self::DECEASED,
            self::UNKNOWN_ERROR
        ];
    }
}


