<?php
/**
 * ApiClient.php
 * PHP version 7.3
 *
 * @category Class
 * @package  Avalara\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Avalara Shipping Verification for Beverage Alcohol
 *
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta.
 *
 * The version of the OpenAPI document: 2.1.0-beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Avalara\SDK;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Avalara\SDK\ApiException;
use Avalara\SDK\Configuration;
use Avalara\SDK\HeaderSelector;
use Avalara\SDK\ObjectSerializer;
use Avalara\SDK\TokenMetadata;
use Ds\Map;

/**
 * ApiClient Class Doc Comment
 *
 * @category Class
 * @package  Avalara\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApiClient
{
    /**
     * @var GuzzleHttp\Client
     */
    public $client;

    /**
     * @var string
     */
    public $sdkVersion;

    /**
     * @var Configuration
     */
    public $config;

    /**
     * @var HeaderSelector
     */
    public $headerSelector;

    /**
     * @var Map
     */
    public $accessTokenMap;

    /**
     * @var string
     */
    public $tokenUrl;

    public $PRODUCTION_OPENID_CONFIG_URL = 'https://identity.avalara.com/.well-known/openid-configuration';
    public $SANDBOX_OPENID_CONFIG_URL = 'https://ai-sbx.avlr.sh/.well-known/openid-configuration';
    public $QA_OPENID_CONFIG_URL = 'https://ai-awsfqa.avlr.sh/.well-known/openid-configuration';
    
    /**
     * @param Configuration   $config
     */
    public function __construct(
        Configuration $config = null
    ) {

        if (is_null($config)){
            throw new ApiException("Configuration is not set or null");
        }

        $this->accessTokenMap = new \Ds\Map();

        $this->config = $config;
        $this->environment = $this->config->getEnvironment();
        
        if (strtolower($this->environment)=="sandbox"){
            $this->config->setHost('https://sandbox-rest.avatax.com');
        }
        elseif(strtolower($this->environment)=="qa"){
            $this->config->setHost("https://qa-rest.avatax.com");
        }
        elseif(strtolower($this->environment)=="production"){
            $this->config->setHost("https://rest.avatax.com");
        }
        elseif(strtolower($this->environment)=="test"){
            if (is_null($this->config->getTestBasePath())) {
                throw new ApiException("TestBasePath must be passed into the config object when environment=\"test\".");
            } else {
                $this->config->setHost($this->config->getTestBasePath());
            }
        }
        else{
            throw new ApiException("Environment is not set correctly.");
        }

        $this->client = new Client();
                
        $this->headerSelector =  new HeaderSelector();
    }

    /**
     * Sets the sdkVersion
     *
     * @param string $sdkVersion 
     *
     * @return $this
     */
    public function setSdkVersion($sdkVersion)
    {
        $this->sdkVersion = $sdkVersion;
        return $this;
    }

    /**
     * Sets the tokenUrl
     *
     *
     * @return $this
     */
    public function setTokenUrl()
    {
        $environment = $this->config->environment;
        $testTokenUrl = $this->config->getTestTokenUrl();
        if (strtolower($environment)=="test") {
            $this->tokenUrl = $testTokenUrl;
        } else if (is_null($this->tokenUrl) || strlen($this->tokenUrl) == 0) {
            try {
                $request = new Request('GET', $this->getOpenIdConnectUrl());
                $response = $this->send_sync($request, []);
                $content = (string) $response->getBody();
                $oidcResponse = json_decode($content);
                $this->tokenUrl = $oidcResponse->token_endpoint;
            } catch (Exception $e) {
                echo 'Exception when calling OpenIdConnect to fetch the token endpoint: ',  $e->getMessage(), "\n";
                throw new ApiException('Exception when calling OpenIdConnect to fetch the token endpoint: '.  $e->getMessage());
            }
        }
        return $this;
    }

    public function getOpenIdConnectUrl() {
        $environment = strtolower($this->config->environment);
        switch ($environment) {
            case "production":
                return $this->PRODUCTION_OPENID_CONFIG_URL;
            case "sandbox":
                return $this->SANDBOX_OPENID_CONFIG_URL;
            case "qa":
                return $this->QA_OPENID_CONFIG_URL;
        }
    }

    /**
     * Adds appropriate Authentication header to the array of headers passed in
     *
     * @param Array $headers 
     *
     * @return $headers
     */
    public function applyAuthToRequest($headers, $requiredScopes) {
        $bearerToken = $this->config->getBearerToken();
        $clientId = $this->config->getClientId();
        $clientSecret = $this->config->getClientSecret();
        $username = $this->config->getUserName();
        $password = $this->config->getPassword();

        if (!is_null($bearerToken)) {
            $headers['Authorization'] = 'Bearer ' . $bearerToken;
        } elseif (!is_null($clientId) && !is_null($clientSecret)) {
            $scopes = $this->standardizeScopes($requiredScopes);
            $accessToken = $this->getOAuthAccessToken($scopes);
            if (is_null($accessToken)) {
                $this->updateOAuthAccessToken($scopes, null);
                $accessToken = $this->getOAuthAccessToken($scopes);
            }
            $headers['Authorization'] = 'Bearer ' . $accessToken;
        } elseif (!is_null($username) && !is_null($password)) {
            $headers['Authorization'] = 'Basic ' . base64_encode($username . ":" . $password);
        }
        return $headers;
    }

    private function standardizeScopes($requiredScopes) {
        $strArray = explode(' ', $requiredScopes);
        sort($strArray);
        return implode(' ', $strArray);
    }

    private function getOAuthAccessToken($scopes) {
        $tokenMetadata = null;
        if ($this->accessTokenMap->hasKey($scopes)) {
            $tokenMetadata = $this->accessTokenMap->get($scopes);
        }
        if (!is_null($tokenMetadata)) {
            $accessToken = $tokenMetadata->accessToken;
            $expiry = $tokenMetadata->expiry;
            $expirationTime = time() + 300;
            if ($expirationTime < $expiry) {
                return $accessToken;
            }
        }
        return null;
    }

    private function updateOAuthAccessToken($scopes, $accessToken) {
        $currentAccessToken = $this->getOAuthAccessToken($scopes);
        if (is_null($currentAccessToken) || $currentAccessToken == $accessToken) {
            try {
                $data = $this->buildOAuthRequest($scopes);
                $timestamp = time() + $data->expires_in;
                $tokenMetadata = new TokenMetadata($data->access_token, $timestamp);
                $this->accessTokenMap->put($scopes, $tokenMetadata);
            } catch (Exception $e) {
                echo 'OAuth2 Token retrieval failed. Error: ',  $e->getMessage(), "\n";
                throw new ApiException('OAuth2 Token retrieval failed. Error: '.  $e->getMessage());
            }
        }
    }

    private function buildOAuthRequest($scopes) {
        $this->setTokenUrl();
        $httpBody = 'grant_type=client_credentials&scope=' . $scopes . '&client_id=' . $this->config->getClientId();
        $headers = [];
        $headers['Content-Type'] = 'application/x-www-form-urlencoded';
        $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getClientId());
        // $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getClientId() . ":" . $this->config->getClientSecret());
        $headers['Accept'] = 'application/json';
        $request = new Request('POST', $this->tokenUrl, $headers, $httpBody);
        $response = $this->send_sync($request, []);
        $content = (string) $response->getBody();
        return json_decode($content);
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }


    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
       
    /**
     * Operation send_sync
     *
     * Executes http request synchronously
     *
     * @param  GuzzleHttp\Request
     * @param array of http client options
     * @param  \returnType
     * @throws \Avalara\SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return Http response
     */
    public function send_sync($request, $options)
    {
        return $this->client->send($request, $options);
    }

     /**
     * Operation send_async
     *
     * Executes http request synchronously
     *
     * @param  GuzzleHttp\Request
     * @param array of http client options
     * @param  \returnType
     * @throws \Avalara\SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return Http response
     */
    public function send_async($request, $options)
    {
        return $this->client->sendAsync($request, $options);
    }

    /**
     * Operation exec_sync_http_request
     *
     * Executes http request synchronously
     *
     * @param  GuzzleHttp\Request
     * @param array of http client options
     * @param  \returnType
     * @throws \Avalara\SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return Http response
     */
    public function exec_async_http_request($request, $options)
    {
        return $this->client
            ->sendAsync($request, $options)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

}
